version: '3.8'

services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=url_shortener
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: ./packages/auth-service
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DB_HOST=admin
      - DB_PORT=5432
      - DB_NAME=url_shortener
      - DB_USER=postgres
      - DB_PASS=1234
      - JWT_SECRET=your_jwt_secret
      - ENABLE_LOGGING=true

  url-service:
    build:
      context: ./packages/url-service
    ports:
      - "3002:3002"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - PORT=3002
      - DB_HOST=admin
      - DB_PORT=5432
      - DB_NAME=url_shortener
      - DB_USER=postgres
      - DB_PASS=1234
      - JWT_SECRET=your_jwt_secret
      - BASE_URL=http://localhost:3000/
      - ENABLE_LOGGING=true

  api-gateway:
    build:
      context: ./packages/api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - url-service
    environment:
      - NODE_ENV=development
      - PORT=3000
      - AUTH_SERVICE_URL=http://auth-service:3001
      - URL_SERVICE_URL=http://url-service:3002
      - ENABLE_LOGGING=true

volumes:
  postgres_data: